apiVersion: v1
kind: Service
metadata:
  name: cleanup-svc
spec:
  selector:
    app: cleanup-svc
  ports:
    - name: tcp-trigger
      port: 55000
      targetPort: 55000
      protocol: TCP
  type: ClusterIP
